export type Language = "en" | "hi";
export type Localized = Record<Language, string>;

export const clinic = {
  name: { en: "Aarogya Vision Clinic", hi: "आरोग्य विज़न क्लिनिक" },
  doctor: "Dr. [Doctor Name]",
  qualification: "[Qualification & Fellowship]",
  phone: "+91 00000 00000",
  phoneHref: "tel:+910000000000",
  whatsapp: "910000000000",
  email: "care@yourclinic.in",
  address: "[Full Clinic Address], [City / District], Bihar — [PIN Code]",
  hours: "Mon–Sat · 9:00 AM–7:00 PM",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Eye+Clinic+Bihar",
};

export const copy = {
  en: {
    nav: ["Home", "About", "Services", "Doctors", "Technology", "Testimonials", "FAQ", "Contact"],
    navIds: ["home", "about", "services", "doctors", "technology", "testimonials", "faq", "contact"],
    book: "Book Appointment", call: "Call Clinic", whatsapp: "WhatsApp Consultation",
    badge: "Advanced eye care in Bihar",
    heroTitle: "Clearer Vision.\nBetter Life.",
    heroText: "Advanced eye care with experienced doctors, modern technology and compassionate treatment for your entire family.",
    trust: ["Experienced eye specialists", "Modern diagnostic technology", "Patient-centric care", "Easy appointment booking"],
    founderEyebrow: "Clinical excellence, personal care", founderTitle: "Meet Our Founder & Lead Eye Specialist",
    founderRole: "Founder · Consultant Ophthalmologist", founderSpeciality: "[Specialization — to be confirmed]",
    founderQuote: "“Our goal is to make high-quality eye care accessible to every family while maintaining the highest standards of medical care, technology and compassion.”",
    profile: "View Doctor Profile", clinicWhatsapp: "WhatsApp Doctor’s Clinic",
    years: "[10+ Years]", yearsLabel: "Experience", patients: "[20,000+]", patientsLabel: "Patients treated",
    servicesEyebrow: "Complete eye care", servicesTitle: "Specialist care for every stage of life",
    servicesIntro: "From a routine vision check to advanced treatment planning, every consultation begins with careful listening and clear guidance.",
    learn: "Learn more", consult: "Book consultation",
    whyEyebrow: "Why choose us", whyTitle: "Why patients trust us",
    whyIntro: "Thoughtful care, transparent advice and an experience designed around your comfort.",
    cataractEyebrow: "Featured treatment", cataractTitle: "See Life Clearly Again",
    cataractText: "A calm, step-by-step cataract consultation with modern assessment, clear lens guidance and support before and after treatment.",
    cataractCta: "Consult Cataract Specialist",
    technologyEyebrow: "Precision-led care", technologyTitle: "Advanced Eye Care Technology",
    technologyText: "Careful examination supported by modern diagnostics. Equipment shown is illustrative and will be updated to match the clinic’s verified facilities.",
    teamEyebrow: "People behind your care", teamTitle: "Meet Our Eye Care Team",
    journeyEyebrow: "Simple from the start", journeyTitle: "Your visit, in four easy steps",
    reviewsEyebrow: "Patient experiences", reviewsTitle: "What Our Patients Say",
    reviewNote: "Demo content — replace with verified patient reviews before publishing.",
    prepareEyebrow: "Before visiting", prepareTitle: "Preparing for Your Appointment",
    faqEyebrow: "Helpful answers", faqTitle: "Frequently Asked Questions",
    ctaTitle: "Your Vision Deserves Expert Care.", ctaText: "Talk to our clinic team today. No account, no complicated form — just a simple call or WhatsApp message.",
    directions: "Get Directions", callNow: "Call Now", contactEyebrow: "Visit the clinic", contactTitle: "Eye care, closer to home",
    contactText: "Find our verified contact information, opening hours and location here before the website goes live.",
    details: "Clinic details", hoursLabel: "Opening hours", emergency: "Emergency contact", emergencyText: "Please call the clinic before travelling for urgent care.",
    mapPlaceholder: "Clinic map will appear here once the verified Google Maps location is added.", openMaps: "Open in Google Maps",
    footerText: "Modern specialist eye care with a human touch, for families across Bihar.",
    placeholder: "Details to be confirmed", larger: "Increase text size", normal: "Reset text size", menu: "Open navigation menu",
  },
  hi: {
    nav: ["होम", "हमारे बारे में", "सेवाएं", "डॉक्टर", "तकनीक", "मरीज़ों की राय", "सवाल", "संपर्क"],
    navIds: ["home", "about", "services", "doctors", "technology", "testimonials", "faq", "contact"],
    book: "अपॉइंटमेंट बुक करें", call: "क्लिनिक को कॉल करें", whatsapp: "WhatsApp पर सलाह लें",
    badge: "बिहार में आधुनिक नेत्र देखभाल",
    heroTitle: "बेहतर नज़र।\nबेहतर ज़िंदगी।",
    heroText: "अनुभवी डॉक्टरों, आधुनिक जांच और पूरे परिवार के लिए संवेदनशील देखभाल के साथ बेहतर आंखों का इलाज।",
    trust: ["अनुभवी नेत्र विशेषज्ञ", "आधुनिक जांच तकनीक", "मरीज़-केंद्रित देखभाल", "आसान अपॉइंटमेंट"],
    founderEyebrow: "बेहतर इलाज, व्यक्तिगत देखभाल", founderTitle: "हमारे संस्थापक और मुख्य नेत्र विशेषज्ञ से मिलें",
    founderRole: "संस्थापक · नेत्र रोग विशेषज्ञ", founderSpeciality: "[विशेषज्ञता — पुष्टि बाकी]",
    founderQuote: "“हमारा उद्देश्य हर परिवार तक उच्च गुणवत्ता वाली नेत्र देखभाल पहुंचाना है—बेहतर चिकित्सा, आधुनिक तकनीक और संवेदनशीलता के साथ।”",
    profile: "डॉक्टर की प्रोफ़ाइल देखें", clinicWhatsapp: "क्लिनिक से WhatsApp पर बात करें",
    years: "[10+ वर्ष]", yearsLabel: "अनुभव", patients: "[20,000+]", patientsLabel: "मरीज़ों का इलाज",
    servicesEyebrow: "संपूर्ण नेत्र देखभाल", servicesTitle: "हर उम्र के लिए विशेषज्ञ देखभाल",
    servicesIntro: "सामान्य नज़र की जांच से लेकर इलाज की योजना तक—हर परामर्श ध्यान से सुनने और साफ़ जानकारी देने से शुरू होता है।",
    learn: "और जानें", consult: "परामर्श बुक करें",
    whyEyebrow: "हमें क्यों चुनें", whyTitle: "मरीज़ हम पर भरोसा क्यों करते हैं",
    whyIntro: "सोच-समझकर इलाज, साफ़ सलाह और आपकी सुविधा को ध्यान में रखकर बनाया गया अनुभव।",
    cataractEyebrow: "विशेष इलाज", cataractTitle: "दुनिया को फिर साफ़ देखें",
    cataractText: "आधुनिक जांच, सही लेंस की स्पष्ट जानकारी और इलाज से पहले व बाद तक पूरी सहायता के साथ मोतियाबिंद परामर्श।",
    cataractCta: "मोतियाबिंद विशेषज्ञ से सलाह लें",
    technologyEyebrow: "सटीक जांच", technologyTitle: "आधुनिक नेत्र जांच तकनीक",
    technologyText: "आधुनिक तकनीक की मदद से सावधानीपूर्वक जांच। दिखाई गई मशीनें उदाहरण हैं; क्लिनिक की सही सुविधाओं के अनुसार इन्हें बदला जाएगा।",
    teamEyebrow: "आपकी देखभाल करने वाली टीम", teamTitle: "हमारी आई केयर टीम से मिलें",
    journeyEyebrow: "शुरू से आसान", journeyTitle: "चार आसान चरणों में आपकी विज़िट",
    reviewsEyebrow: "मरीज़ों के अनुभव", reviewsTitle: "हमारे मरीज़ क्या कहते हैं",
    reviewNote: "डेमो सामग्री — प्रकाशित करने से पहले सही मरीज़ समीक्षाएं जोड़ें।",
    prepareEyebrow: "आने से पहले", prepareTitle: "अपॉइंटमेंट की तैयारी",
    faqEyebrow: "ज़रूरी जवाब", faqTitle: "अक्सर पूछे जाने वाले सवाल",
    ctaTitle: "आपकी आंखें विशेषज्ञ देखभाल की हकदार हैं।", ctaText: "आज ही हमारी क्लिनिक टीम से बात करें। कोई अकाउंट या लंबा फॉर्म नहीं—सिर्फ़ कॉल या WhatsApp।",
    directions: "रास्ता देखें", callNow: "अभी कॉल करें", contactEyebrow: "क्लिनिक आएं", contactTitle: "बेहतर नेत्र देखभाल, आपके पास",
    contactText: "वेबसाइट प्रकाशित होने से पहले यहां क्लिनिक का सही पता, समय और संपर्क जानकारी जोड़ी जाएगी।",
    details: "क्लिनिक की जानकारी", hoursLabel: "खुलने का समय", emergency: "आपातकालीन संपर्क", emergencyText: "तुरंत इलाज के लिए निकलने से पहले क्लिनिक को कॉल करें।",
    mapPlaceholder: "सही Google Maps लोकेशन मिलने के बाद यहां क्लिनिक का नक्शा दिखाई देगा।", openMaps: "Google Maps में खोलें",
    footerText: "बिहार के परिवारों के लिए संवेदनशीलता के साथ आधुनिक विशेषज्ञ नेत्र देखभाल।",
    placeholder: "जानकारी की पुष्टि बाकी", larger: "अक्षर बड़े करें", normal: "अक्षर सामान्य करें", menu: "नेविगेशन मेन्यू खोलें",
  },
};

export const services = [
  ["Comprehensive Eye Examination", "संपूर्ण आंखों की जांच", "A detailed check of vision and overall eye health.", "नज़र और आंखों के पूरे स्वास्थ्य की विस्तृत जांच।"],
  ["Cataract Consultation & Surgery", "मोतियाबिंद परामर्श और सर्जरी", "Clear assessment, lens guidance and treatment planning.", "जांच, सही लेंस की जानकारी और इलाज की योजना।"],
  ["Glaucoma Screening & Treatment", "काला मोतिया जांच और इलाज", "Pressure checks and careful optic nerve evaluation.", "आंखों के दबाव और ऑप्टिक नर्व की सावधानीपूर्वक जांच।"],
  ["Retina & Diabetic Eye Care", "रेटिना और डायबिटिक आई केयर", "Retina evaluation for diabetes and vision concerns.", "डायबिटीज और नज़र की समस्याओं के लिए रेटिना जांच।"],
  ["Children’s Eye Care", "बच्चों की आंखों की देखभाल", "Comfortable, age-appropriate eye and vision checks.", "बच्चों के लिए सहज और उम्र के अनुसार आंखों की जांच।"],
  ["Dry Eye & Digital Eye Strain", "सूखी आंखें और स्क्रीन से परेशानी", "Relief plans for dryness, irritation and screen fatigue.", "सूखापन, जलन और स्क्रीन की थकान के लिए सलाह।"],
  ["Cornea & Eye Infection Care", "कॉर्निया और आंखों के संक्रमण का इलाज", "Prompt assessment for redness, pain and infection.", "लालिमा, दर्द और संक्रमण की समय पर जांच।"],
  ["Vision & Contact Lens Consultation", "नज़र और कॉन्टैक्ट लेंस परामर्श", "Accurate power testing and personalized lens advice.", "सही पावर जांच और आपके लिए लेंस की सलाह।"],
];

export const faqs = [
  ["How can I book an appointment?", "मैं अपॉइंटमेंट कैसे बुक कर सकता/सकती हूँ?", "Tap the WhatsApp or Call button anywhere on this page. Our clinic team will help confirm a suitable time.", "इस पेज पर WhatsApp या कॉल बटन दबाएं। हमारी टीम आपके लिए सही समय तय करने में मदद करेगी।"],
  ["Do I need an appointment before visiting?", "क्या आने से पहले अपॉइंटमेंट ज़रूरी है?", "An appointment is recommended to reduce waiting. Please call before travelling for urgent care.", "इंतज़ार कम करने के लिए अपॉइंटमेंट लेना बेहतर है। तुरंत इलाज के लिए आने से पहले कॉल करें।"],
  ["What are the clinic timings?", "क्लिनिक का समय क्या है?", "The displayed hours are placeholders and will be updated with the clinic’s verified schedule before launch.", "दिखाया गया समय अभी उदाहरण है। प्रकाशित करने से पहले क्लिनिक का सही समय जोड़ा जाएगा।"],
  ["Is cataract consultation available?", "क्या मोतियाबिंद का परामर्श मिलता है?", "Yes, cataract assessment and treatment guidance are included in the planned services. Final availability must be confirmed with the clinic.", "हाँ, मोतियाबिंद जांच और इलाज की सलाह प्रस्तावित सेवाओं में है। क्लिनिक से उपलब्धता की पुष्टि करें।"],
  ["Do you provide children’s eye checkups?", "क्या बच्चों की आंखों की जांच होती है?", "Children’s eye checks are listed as a planned service and will be confirmed before publishing.", "बच्चों की आंखों की जांच प्रस्तावित सेवा है और प्रकाशित करने से पहले इसकी पुष्टि की जाएगी।"],
  ["How long does an eye examination take?", "आंखों की जांच में कितना समय लगता है?", "The duration depends on the tests needed. Some examinations, including dilation, may take longer.", "समय ज़रूरी जांचों पर निर्भर करता है। पुतली फैलाने वाली जांच में अधिक समय लग सकता है।"],
  ["Can I contact the clinic through WhatsApp?", "क्या मैं WhatsApp से संपर्क कर सकता/सकती हूँ?", "Yes. The WhatsApp button opens a ready-to-send appointment message.", "हाँ। WhatsApp बटन अपॉइंटमेंट के लिए तैयार संदेश खोलता है।"],
  ["Do you provide emergency consultation?", "क्या आपातकालीन परामर्श मिलता है?", "Please call the clinic first so the team can guide you based on availability and urgency.", "पहले क्लिनिक को कॉल करें ताकि टीम उपलब्धता और ज़रूरत के अनुसार सही सलाह दे सके।"],
];